---
title: "Philly AQI"
author: "Ally Racho"
date: "2/10/2022"
output:
  pdf_document: default
  html_document: default
---
```{r}
library("jsonlite")

#########################
# Philadelphia AQI
##########################
#philly 2018 aqi 
result <- fromJSON("./Data/PhillyAQI2018.json")
phillyAQI2018 <- as.data.frame(result)

#philly 2019 aqi 
result <- fromJSON("./Data/PhillyAQI2019.json")
phillyAQI2019 <- as.data.frame(result)

#philly 2021 aqi
result <- fromJSON("./Data/PhillyAQI2020.json")
phillyAQI2021 <- as.data.frame(result)

#philly 2020 aqi
result <- fromJSON("./Data/PhilllyAQI2021.json")
phillyAQI2020 <- as.data.frame(result)

#combine all years to one dataset
df_list <- list(phillyAQI2018, phillyAQI2019, phillyAQI2020, phillyAQI2021)
PhillyAQI <- Reduce(function(x,y)merge(x,y,all = TRUE), df_list, accumulate = FALSE)

write.csv(PhillyAQI, file = "./Data/PhillyAQI.csv")

```

```{r}
library(DataExplorer)
```

```{r}
introduce(PhillyAQI)
```
```{r}
plot_intro(PhillyAQI)
```
```{r}
plot_missing(PhillyAQI)
```
```{r}
plot_histogram(PhillyAQI$Data.sample_measurement, title = 'Philadelphia AQI Sample Measurements')

```
```{r}
plot_qq(PhillyAQI$Data.sample_measurement)
```
```{r}
sample_meas <- PhillyAQI[, c("Data.sample_measurement", "Data.date_local")]

plot_scatterplot(sample_meas, by = "Data.date_local", sampled_rows = 1000L)
```

