---
title: "Philly Pollution"
author: "Ally Racho"
date: "2/8/2022"
output:
  pdf_document: default
  html_document: default
---

#load EDA library 
```{r}
library(DataExplorer)
library(tidyverse)
library(readr)
camden_spruce_st_newjersey_usa_air_quality <- read_csv("Data/camden-spruce st, newjersey, usa-air-quality.csv")
```
#summarize data statistically 
```{r}
summary(camden_spruce_st_newjersey_usa_air_quality)
```

```{r}
plot_str(camden_spruce_st_newjersey_usa_air_quality)
```

```{r}
plot_intro(camden_spruce_st_newjersey_usa_air_quality)
```
#Histogram of pollutants
```{r}
plot_histogram(camden_spruce_st_newjersey_usa_air_quality)
```

```{r}
qq_plot <- plot_qq(camden_spruce_st_newjersey_usa_air_quality)
```
#co, no2, pm25 appear skewed on both tails -- log transform and replot

```{r}
#log_qq_data <- update_columns(qq_plot, c(1, 2, 4), function(x) log(x + 1))
#plot_qq(log_qq_data[, 1:2], sampled_rows = 1000L)
#plot_qq(log_qq_data[, 4], sampled_rows = 1000L)
```

#correlation matrix excluding NAs
```{r}
plot_correlation(na.omit(camden_spruce_st_newjersey_usa_air_quality), maxcat = 5L)
```

```{r}
pca_df <- na.omit(camden_spruce_st_newjersey_usa_air_quality[, c("pm25", "o3", "no2", "so2", "co")])
plot_prcomp(pca_df, variance_cap = 0.9, nrow = 2L, ncol = 2L)
```

```{r}
plot_boxplot(camden_spruce_st_newjersey_usa_air_quality, by = 'date')
```
```{r}
plot_scatterplot(camden_spruce_st_newjersey_usa_air_quality, by = 'date')
```

